### ISSUE TITLE
v1.0.0 Roadmap

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg#332]
I think it's time to start talking about what needs to happen for NodeCG to have a stable v1.0.0 release.

Off the top of my head, these are the things I would like to have as part of a v1 release:

- [x] ~New docs site ([nodecg.com](http://nodecg.com)), with~ better docs ~to accompany it~ (#406)
- [x] Increased test coverage. I think 90% seems like a good goal.
- [x] Support for local username/password authentication, rather than needing to rely on Twitch or Steam authentication.
- [x] Update [`generator-nodecg`](https://github.com/nodecg/generator-nodecg) to support the current NodeCG featureset.
    - Calling it good enough for now. Will publish v1.0 of the generator as soon as v1.0 of NodeCG itself goes live.
- [x] Support multiple listenFor handlers for a given message in a given context (#298)
- [x] Emit message events within a given context, so that sendMessage/listenFor can be used as an events bus within a context (#410)
- [x] ~Port to Polymer 3~

Additional suggestions/requests for things to have in a v1.0 release are welcome.

EDIT: I will be editing the above list as new things are thought of.

**Comment by madmatt** [comment]
Do you have any plans for the new docs site? I'd be keen to help contribute some docs, but not sure if you're thinking about taking the docs out of the repo or changing up how they're managed?

**Comment by Lange** [comment]
@madmatt At this time I don't have any actionable plans. I suppose that sitting down, thinking about what the goals are, and creating an action plan would be the first step I need help with haha

**Comment by MattMcNam** [comment]
I've wanted local auth for ages so I'm gonna get started on that now, and if I think of any others I'll post them here

**Comment by Lange** [comment]
I've added a new item to this roadmap: Port to Polymer 3.

Polymer 3.0 is likely to be out sometime in the next few months. I'm not 100% convinced that the initial 3.0 release will have everything we want, and we might need to wait for some of the tooling to mature before we undergo this port.

Porting to Polymer 3.0 as part of the 1.0 roadmap is good, because porting to 3.0 would probably be a breaking change. It makes sense to batch breaking changes together as much as we can.

**Comment by Lange** [comment]
I've thought about it more and do not think we should port to Polymer 3 as part of a 1.0 release.

I've already elaborated on this in a few places (including Discord), but here's a link to a comment which mostly explains my stance: https://github.com/nodecg/nodecg/issues/395#issuecomment-391088106

**Comment by Lange** [comment]
There are now basic login authentication tests, added in #404.

Right now it's just 2 tests, but those 2 got us an additional 5% coverage. That much closer to our 90% coverage goal. Any help, even people just writing single tests to get a tiny bit more coverage, is extremely appreciated.

**Comment by Lange** [comment]
https://github.com/nodecg/nodecg/commit/e1717c4ea4d2bed8f7e2b2da9244520854518e64 improved the accuracy of our browser code coverage reporting. I'm not sure if it's completely accurate yet, but it seems _more_ accurate, at least.

**Comment by Lange** [comment]
We have achieved 90% test coverage as of this build: https://codecov.io/gh/nodecg/nodecg/commit/6366d88229ab9838e546125d786cb22b1f974908

**Comment by Lange** [comment]
A PR for intra-context messaging has been opened, reviewers wanted: https://github.com/nodecg/nodecg/pull/410

**Comment by Lange** [comment]
Closed by https://github.com/nodecg/nodecg/commit/64bf96caba3b3d3da3f97f5a554cda5ad0bf72bd
